config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'prototypes#index'
  resources :prototypes do
    resources :likes, only: [:create,:destroy]
    resources :comments, only: [:create,:destroy]
  end
  resources :populars, only: [:index]
  resources :newests, only: [:index]
  resources :users, only: [:show,:edit,:update]
  resources :tags, only: [:index,:show]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :proto
end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :photo, ImageUploader

  belongs_to :proto
  
  enum status: %i(main sub)

  validates :photo, presence: true

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :proto, counter_cache: :likes_count
end

app/models/proto.rb
class Proto < ActiveRecord::Base
  has_many :images, dependent: :delete_all
  belongs_to :user
  has_many :likes, dependent: :delete_all
  has_many :comments,dependent: :delete_all

  accepts_nested_attributes_for :images

  def self.pagination_newest_per(param)
    includes(:images,:user).order("created_at DESC").page(param).per(10)
  end

  def self.pagination_popular_per(param)
    includes(:images,:user).order("likes_count DESC").page(param).per(10)
  end

  def self.pagination_prototype_per(param)
    includes(:images,:user).page(param).per(10)
  end

  def images_sub
    images.sub
  end

  def image_main_photo
    images.main.first.photo
  end

  def like_user(user)
   likes.find_by(user_id: user)
  end

  acts_as_taggable 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  has_many :protos,dependent: :delete_all
  has_many :likes,dependent: :delete_all
  has_many :comments,dependent: :delete_all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile, :position, :occupation, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :position, :occupation, :avatar])
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:create,:destroy]

  def create
    Comment.create(comment_params)
  end

  def destroy
    comment = Comment.find_by(proto_id: params[:prototype_id],user_id: current_user.id)
    comment.destroy
  end

  private
  def comment_params
    params.require(:comment).permit(:comment_text).merge(user_id: current_user.id,proto_id: params[:prototype_id])
  end

  def set_comment
    @comments = Comment.where(proto_id: params[:prototype_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = Like.create(proto_id:params[:prototype_id],user_id: current_user.id)
    @prototype = Proto.find(params[:prototype_id])
    @likes = Like.where(prototype_id: params[:prototype_id])
  end

  def destroy
    like = Like.find_by(proto_id:params[:prototype_id],user_id: current_user.id)
    like.destroy
    @prototype = Proto.find(params[:prototype_id])
    @likes = Like.where(prototype_id: params[:prototype_id])
  end
end

app/controllers/newests_controller.rb
class NewestsController < ApplicationController
  def index
    @prototypes = Proto.pagination_newest_per(params[:page])
  end
end

app/controllers/populars_controller.rb
class PopularsController < ApplicationController
  def index
    @prototypes = Proto.pagination_popular_per(params[:page])
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController

  before_action :set_prototype, only: [:edit,:update,:destroy,:show]
  before_action :set_photo, only: [:show,:edit]

  def index
    @prototypes = Proto.pagination_prototype_per(params[:page])
  end

  def new
    @prototypes = Proto.new
    @prototypes.images.build
  end

  def create
    @prototypes = Proto.new(proto_params)
    if @prototypes.save
      redirect_to :root,notice: 'upload complete'
    else
      redirect_to action: "new", alert: 'Not complete'
    end
  end

  def show
    @prototype.likes
    @comment = Comment.new
    @prototype.comments
  end

  def edit
  end

  def destroy
    @prototype.destroy
    redirect_to :root, notice: 'You could destroy your prototype.'
  end

  def update
    if @prototype.update(proto_params)
      redirect_to action: show, notice: 'You could edit your prototype.'
    else
      redirect_to action: edit , alert: 'You cannot edit your prototype.'
    end
  end

  private
  def proto_params
    params.require(:proto).permit(:title, :catch_copy, :concept, images_attributes: [:id, :photo, :status]).merge(user_id: current_user.id,tag_list: params[:proto][:tag])
  end

  def set_prototype
    @prototype = Proto.find(params[:id])
  end

  def set_photo
    set_prototype
    @sub_photo = @prototype.images_sub
    @main_photo = @prototype.image_main_photo
  end
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @tag = ActsAsTaggableOn::Tag.find(params[:id])
    @prototypes = Proto.tagged_with(@tag).pagination_prototype_per(params[:page])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update]
  before_action :authenticate_user!, only: [:edit,:update]

  def show
    @prototypes = @user.protos
  end

  def edit
  end

  def update
    @user.update(update_params)
    redirect_to :root, notice: 'You can edit your profile.'
  end

  private
  def update_params
    params.require(:user).permit(:name,:email,:position,:profile,
      :occupation)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/views/comments/_comment.html.haml
%p
  = link_to user_path(comment.user) do
    =image_tag(comment.user.avatar,width: "64",height: "64")
  = comment.comment_text
  - if current_user.id == comment.user_id
    = link_to "DELETE",prototype_comment_path(comment.proto,comment),method: :delete,remote: true

app/views/comments/create.js.erb
$("#js-comment-text").val("");
$(".media-comment").html("<%= j(render @comments) %>");

app/views/comments/destroy.js.erb
$(".media-comment").html("<%= j(render @comments) %>");

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.
  

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/")
      = image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px")
    .navbar-collapse.collapse.navbar-responsive-collapse
      -if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{ aria: { expanded: true }, data: { toggle: :dropdown }, href: "#", role: "button"}
              #{current_user.name}
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                =link_to 'My page',user_path(current_user)
              %li
                =link_to 'Edit',edit_user_path(current_user)
              %li
                =link_to 'Logout',destroy_user_session_path, method: :delete
          %li
            .btn.btn-primary.navbar-btn
              %a{href: "/prototypes/new"}
                New Proto
      -else
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              =link_to 'GET START',new_user_session_path

app/views/layouts/_message.html.haml
-flash.each do |key,value|
  %a{href: "#", "data-dismiss": "alert", class: "close"}×
  = content_tag :div, value,class: "alert alert-#{key}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=US-ASCII", "http-equiv" => "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    = render "layouts/message"
    = yield
    = render "layouts/footer"

app/views/likes/create.js.erb
$(".col-md-6.text-right.like-button").html("<%= j(render partial: 'prototypes/like') %>");

app/views/likes/destroy.js.erb
$(".col-md-6.text-right.like-button").html("<%= j(render partial: 'prototypes/like') %>");

app/views/newests/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          =link_to 'Popular PROTO',populars_path
        %li{role: "presentation"}
          =link_to 'Newest PROTO',newests_path
      %button{type: "button", class: "btn btn-default col-lg-1"} View Tags

.container.proto-list
  .row
    =render partial: 'prototypes/prototype', collection: @prototypes
.text-center
  %ul.pagination
    =paginate(@prototypes)

app/views/populars/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          =link_to 'Popular PROTO',populars_path
        %li{role: "presentation"}
          =link_to 'Newest PROTO',newests_path
      %button{type: "button", class: "btn btn-default col-lg-1"} View Tags

.container.proto-list
  .row
    =render partial: 'prototypes/prototype', collection: @prototypes
.text-center
  %ul.pagination
    =paginate(@prototypes)

app/views/prototypes/_like.html.haml
-if user_signed_in?
  - if @prototype.like_user(current_user.id)
    = button_to prototype_like_path(@prototype,@likes), method: :delete, remote: true, class: 'btn btn-default btn-like' do
      = image_tag("icon_heart_red.svg")
      %strong
        = 'LIKE'
        = @prototype.likes_count
  - else
    = button_to prototype_likes_path(@prototype), method: :create, remote: true,class: 'btn btn-default btn-like' do
      = image_tag("icon_heart.svg")
      %strong
        ='LIKE'
        =@prototype.likes_count
- else
  %btn.btn-default
    = image_tag("icon_heart_red.svg")
    = @prototype.likes_count

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    =link_to image_tag(prototype.image_main_photo), prototype_path(prototype)
    .caption
      %h3
        =prototype.title
      .proto-meta
        .proto-user
          =link_to "#{prototype.user.name}",user_path(prototype.user)
        .proto-posted
          = prototype.created_at.strftime("%Y/%m/%d(#{%w(日 月 火 水 木 金 土)[prototype.created_at.wday]})")
      %ul.proto-tag-list.list-inline
        - prototype.tags.each do |tag|
          %li
            =link_to tag.name,tag_path(tag.id),class: "btn btn-default"

app/views/prototypes/edit.html.haml
.container.proto-new{action: ""}
  = form_for @prototype,url: prototype_path do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          = f.text_field :title, class:".proto-new-title", placeholder: "Title"
      .row
        .col-md-12
          .cover-image-upload
            = f.fields_for :images, @prototype.images.main do |image|
              = image.file_field :photo
              = image.hidden_field :status, value: "main"
          .col-md-12
            %ul.proto-sub-list.list-group
              %li.list-group-item.col-md-4
                .image-upload
                  = f.fields_for :images, @prototype.images.sub.first do |image|
                    = image.file_field :photo
                    = image.hidden_field :status, value: "sub"
              %li.list-group-item.col-md-4
                .image-upload
                  = f.fields_for :images, @prototype.images.sub.second do |image|
                    = image.file_field :photo
                    = image.hidden_field :status, value: "sub"
              %li.list-group-item.col-md-4
                .image-upload-plus
                  %span +
      .row.proto-description
        .col-md-12
          =f.text_field :catch_copy, placeholder: "Catch Copy"
        .col-md-12
          =f.text_area :concept, cols: "30", rows: "4", placeholder: "Concept"
        .col-md-12
          %h4 Tag List
          .row
            .col-md-3
              =text_field_tag 'proto[tag][]',"",placeholder: "Web"
            .col-md-3
              =text_field_tag 'proto[tag][]',"",placeholder: "UI"
            .col-md-3
              =text_field_tag 'proto[tag][]',"",placeholder: "Design"
      .row.text-center.proto-btn
        = f.submit "PUBLISH", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          =link_to 'Popular PROTO',populars_path
        %li.active{role: "presentation"}
          =link_to 'Newest PROTO',newests_path
      = button_tag class: "btn btn-default col-lg-1" do
        = link_to 'view tag',tags_path

.container.proto-list
  .row
    =render partial: 'prototypes/prototype', collection: @prototypes
.text-center
  %ul.pagination
    =paginate(@prototypes)

app/views/prototypes/new.html.haml
.container.proto-new{action: ""}
  = form_for @prototypes,url: prototypes_path do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          = f.text_field :title, class:".proto-new-title", placeholder: "Title"
      .row
        .col-md-12
          = f.fields_for :images do |image|
            .cover-image-upload
              = image.file_field :photo
              = image.hidden_field :status, value: "main"
          .col-md-12
            %ul.proto-sub-list.list-group
              %li.list-group-item.col-md-4
                .image-upload
                  = f.fields_for :images do |image|
                    = image.file_field :photo
                    = image.hidden_field :status, value: "sub"
              %li.list-group-item.col-md-4
                .image-upload
                  = f.fields_for :images do |image|
                    = image.file_field :photo
                    = image.hidden_field :status, value: "sub"
              %li.list-group-item.col-md-4
                .image-upload-plus
                  %span +
      .row.proto-description
        .col-md-12
          =f.text_field :catch_copy, placeholder: "Catch Copy"
        .col-md-12
          =f.text_area :concept, cols: "30", rows: "4", placeholder: "Concept"
        .col-md-12
          %h4 Tag List
          .row
            .col-md-3
              =text_field_tag 'proto[tag][]',"",placeholder: "Web"
            .col-md-3
              =text_field_tag 'proto[tag][]',"",placeholder: "UI"
            .col-md-3
              =text_field_tag 'proto[tag][]',"",placeholder: "Design"
      .row.text-center.proto-btn
        = f.submit "PUBLISH", id: "button", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to user_path(@prototype.user) do
            = image_tag(@prototype.user.avatar,width: "64",height: "64")
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            by
            = link_to "#{@prototype.user.name}", user_path(@prototype.user)
            .degree
              = @prototype.user.position
    .col-md-6.text-right.like-button
      = render 'like'
    .col-md-6.text-left
      .extra-button
        - if user_signed_in? && @prototype.user_id == current_user.id
          .btn.btn-default.navbar-btn
            = link_to "Edit", edit_prototype_path(@prototype)
          .btn.btn-default.navbar-btn
            = link_to "Delete", prototype_path(@prototype), method: :delete

  .row
    .col-md-9
      = image_tag(@main_photo, class: 'img-responsive')
    .col-md-3
      %ul.proto-sub-list.list-group
        - @sub_photo.each do |image|
          %li.list-group-item
            = image_tag(image.photo, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.catch_copy
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        - @prototype.tags.each do |tag|
          %li
            =link_to tag.name,tag_path(tag.id),class: "btn btn-default"
  %h4.col-md-12
    Comments
    %span#comments-number.num
      = @prototype.comments.size
  .col-md-8
    .media
      .media-body
        %h4#top-aligned-media.media-heading
          %a.anchorjs-link{href: "#top-aligned-media"}
            %span.anchorjs-icon
        .media-comment
          = render @prototype.comments
    .form-inline
    - if user_signed_in?
      = form_for @comment,url: prototype_comments_path(@prototype),remote: true do |f|
        %h4 Write a comment
        .row
          .form-group.col-md-10
            = f.text_area :comment_text, rows: "3", placeholder: "Your comments",require: true,id: "js-comment-text", class: "form-control"
          .form-group.col-md-2
            = f.submit "COMMENT", class: "button btn btn-primary"

app/views/tags/index.html.haml
.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          =link_to 'Popular PROTO',populars_path
        %li.active{role: "presentation"}
          =link_to 'Newest PROTO',newests_path
      = button_tag class: "btn btn-default col-lg-1" do
        = link_to 'view tag',tags_path
.container.proto-list
  .row
    - @tags.each do |tag|
      .col-sm-4.col-md-3.proto-content
        .thumbnail
          =button_tag class: "btn btn-tag" do
            = link_to tag.name, tag_path(tag.id)
          .tag-meta
            = link_to "#{tag.taggings_count}projects", tag_path(tag.id), class: "label label-default tag-list-number"

app/views/tags/show.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          =link_to 'Popular PROTO',populars_path
        %li.active{role: "presentation"}
          =link_to 'Newest PROTO',newests_path
      = button_tag class: "btn btn-default col-lg-1" do
        = link_to 'view tag',tags_path


.container.proto-list
  .row
    = render partial: 'prototypes/prototype', collection: @prototypes

.text-center
  %ul.pagination
    = paginate(@prototypes)

app/views/users/edit.html.haml
.container.user-new{action: ""}
  =form_for @user do |f|
    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          %h2 Edit Profile
          .user-name_image.row
            .user-name.col-md-10
              =f.text_field :name, placeholder:"Write your name",autofocus:true,required: true
            .user-image.col-md-2{:style: 'background-image: url(http://泣ける動画.com/wp-content/uploads/2015/01/t0205-01.jpg);'}
            %button.btn.btn-primary Change image
            =f.file_field :avatar
          .user-email
            =f.text_field :email,placeholder: "Wite your email",required: true
          =f.text_field :password, class: ".user-password", placeholder: "Password"
        .col-md-12
          %h4 Member of
          .user-user-member.row
            .user-name.col-md-12
              =f.text_field :position, placeholder: "Member"
          %h4 Profile
          .user-user-profile.row
            .user-name.col-md-12
              = f.text_area :profile, cols: "30", rows: "4", placeholder: "Profile"
          %h4 Works
          .user-name_image.row
            .user-name.col-md-12
              =f.text_area :occupation, cols: "30", rows: "4", placeholder: "Works"
      .row.text-center.user-btn
        =f.submit "Save",id:"button",class: "btn btn-lg btn-primary btn-block"

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        %a{href: "#"}
          %img.media-object
            = image_tag(@user.avatar,width: "64",height: "64")
      .media-body
        %h4#top-aligned-media.media-heading
          = @user.name
          %span.label.label-default.project-number
            29
            %i Projects
        .proto-user
          %span.degree 
            = @user.position
        .row
          .col-md-6
            %h4 Profile
            %p 
              =@user.profile
          .col-md-6
            %h4 Works
            %p 
            =@user.occupation
.container.proto-list
  .row
    =render partial: 'prototypes/prototype', collection: @prototypes